// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXqzIyReZN5oSq6Jc9oZffHqFYx1l2mg',
    appId: '1:123782776535:web:59f0d42a158c1d47e21292',
    messagingSenderId: '123782776535',
    projectId: 'sdcapp-898e8',
    authDomain: 'sdcapp-898e8.firebaseapp.com',
    storageBucket: 'sdcapp-898e8.firebasestorage.app',
    measurementId: 'G-KBSFBCTZS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm0q-tIRPh8H3awTqJMhGb_h6at_N-VTk',
    appId: '1:123782776535:android:d00131b4a326e793e21292',
    messagingSenderId: '123782776535',
    projectId: 'sdcapp-898e8',
    storageBucket: 'sdcapp-898e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdyueP3tP7teRExTpv5jY000sHoKnb1gk',
    appId: '1:123782776535:ios:7e1422ea27c20c94e21292',
    messagingSenderId: '123782776535',
    projectId: 'sdcapp-898e8',
    storageBucket: 'sdcapp-898e8.firebasestorage.app',
    iosClientId: '123782776535-9m81j2d5n3n22st6ivdltut72siddgkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdyueP3tP7teRExTpv5jY000sHoKnb1gk',
    appId: '1:123782776535:ios:7e1422ea27c20c94e21292',
    messagingSenderId: '123782776535',
    projectId: 'sdcapp-898e8',
    storageBucket: 'sdcapp-898e8.firebasestorage.app',
    iosClientId: '123782776535-9m81j2d5n3n22st6ivdltut72siddgkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJXqzIyReZN5oSq6Jc9oZffHqFYx1l2mg',
    appId: '1:123782776535:web:07d1caf97b3206d7e21292',
    messagingSenderId: '123782776535',
    projectId: 'sdcapp-898e8',
    authDomain: 'sdcapp-898e8.firebaseapp.com',
    storageBucket: 'sdcapp-898e8.firebasestorage.app',
    measurementId: 'G-1EXX6GX8FN',
  );
}
